# -*- coding: utf-8 -*-
"""
train_hgconv_direct.py

Direct training script for CARE-4DD + lightweight heterogeneous graph convolution.

This script DOES NOT use my_data.py. It reads data directly from:
    <dataset_path>/active_split/graph_raw_tensors.pt
which is the GNN-ready output produced by data_pipeline_v3.

Expected raw graph package structure:
    pkg['node_features']['Patient']['x']
    pkg['node_features']['Drug']['x']
    pkg['node_features']['Procedure']['x']
    pkg['supervision']['y'], train_mask, val_mask, test_mask
    pkg['edges']['Patient-Drug']['edge_index'] or reverse relation
    pkg['edges']['Patient-Procedure']['edge_index'] or reverse relation

PPR files can be generated by medical_ppr.py and usually look like:
    top_indices_alpha_0.5_medical_drug.npy
    top_values_alpha_0.5_medical_drug.npy
    top_indices_alpha_0.5_medical_proc.npy
    top_values_alpha_0.5_medical_proc.npy

The model file care4dd_hgconv_model.py must be in the same project directory.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

try:
    from sklearn.metrics import accuracy_score, average_precision_score, f1_score, roc_auc_score
except Exception as exc:
    raise ImportError("This script requires scikit-learn for metrics.") from exc

try:
    from care4dd_hgconv_model import CARE4DD_HGConv, CARE4DDHGConvConfig
except Exception as exc:
    raise ImportError(
        "Cannot import care4dd_hgconv_model.py. Please put it in the same directory as train_hgconv_direct.py."
    ) from exc


# =============================================================================
# Basic utils
# =============================================================================

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    if torch.backends.cudnn.is_available():
        torch.backends.cudnn.deterministic = False
        torch.backends.cudnn.benchmark = True


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def to_jsonable(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): to_jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_jsonable(x) for x in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, torch.Tensor):
        return obj.detach().cpu().tolist()
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        v = float(obj)
        return None if math.isnan(v) or math.isinf(v) else v
    return obj


def select_device(args: argparse.Namespace) -> torch.device:
    if args.device == "cpu" or not torch.cuda.is_available():
        return torch.device("cpu")
    if args.device_num is not None and int(args.device_num) >= 0:
        return torch.device(f"cuda:{int(args.device_num)}")
    return torch.device("cuda")


def torch_load(path: Path):
    try:
        return torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(path, map_location="cpu")


# =============================================================================
# Raw graph loading: no my_data.py
# =============================================================================

def resolve_graph_pt(dataset_path: str, split_name: str = "active_split") -> Path:
    p = Path(dataset_path)
    if p.is_file():
        if p.name != "graph_raw_tensors.pt":
            raise FileNotFoundError(f"dataset_path is a file but not graph_raw_tensors.pt: {p}")
        return p
    candidates = [
        p / split_name / "graph_raw_tensors.pt",
        p / "active_split" / "graph_raw_tensors.pt",
        p / "graph_raw_tensors.pt",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError("Cannot find graph_raw_tensors.pt. Tried:\n" + "\n".join(str(c) for c in candidates))


def get_2d_tensor_from_item(item: Dict[str, Any], preferred_key: str = "x") -> torch.Tensor:
    if preferred_key in item and torch.is_tensor(item[preferred_key]) and item[preferred_key].dim() == 2:
        return item[preferred_key].detach().cpu().float()
    for _, v in item.items():
        if torch.is_tensor(v) and v.dim() == 2:
            return v.detach().cpu().float()
    raise KeyError(f"Cannot find 2D feature tensor in keys={list(item.keys())}")


def get_supervision_tensor(sup: Dict[str, Any], key: str, ndim: Optional[int] = None) -> torch.Tensor:
    aliases = {
        "y": ["y", "label", "labels", "patient_y", "Y"],
        "train_mask": ["train_mask", "train", "train_masks", "TRAIN_MASK"],
        "val_mask": ["val_mask", "valid_mask", "validation_mask", "val", "VAL_MASK"],
        "test_mask": ["test_mask", "test", "TEST_MASK"],
    }
    for k in aliases.get(key, [key]):
        if k in sup and torch.is_tensor(sup[k]):
            t = sup[k]
            if ndim is None or t.dim() == ndim:
                return t.detach().cpu()
    # Fallback for labels.
    if key == "y":
        for _, v in sup.items():
            if torch.is_tensor(v) and v.dim() == 1 and v.dtype in (torch.int64, torch.long, torch.int32):
                return v.detach().cpu().long()
    raise KeyError(f"Cannot find supervision tensor '{key}'. supervision keys={list(sup.keys())}")


def load_raw_graph_package(dataset_path: str, split_name: str = "active_split") -> Dict[str, Any]:
    pt_path = resolve_graph_pt(dataset_path, split_name=split_name)
    print(f"[DirectLoader] Loading graph_raw_tensors.pt: {pt_path}", flush=True)
    pkg = torch_load(pt_path)
    if not isinstance(pkg, dict):
        raise ValueError(f"graph_raw_tensors.pt should be a dict, got {type(pkg)}")

    node_features = pkg.get("node_features") or pkg.get("nodes")
    if not isinstance(node_features, dict):
        raise KeyError(f"graph package has no node_features/nodes dict. keys={list(pkg.keys())}")

    for ntype in ["Patient", "Drug", "Procedure"]:
        if ntype not in node_features:
            raise KeyError(f"Missing node type '{ntype}'. Existing node types={list(node_features.keys())}")

    patient_x = get_2d_tensor_from_item(node_features["Patient"])
    drug_x = get_2d_tensor_from_item(node_features["Drug"])
    proc_x = get_2d_tensor_from_item(node_features["Procedure"])

    sup = pkg.get("supervision") or pkg.get("labels") or pkg.get("patient_supervision") or {}
    if not isinstance(sup, dict):
        raise KeyError("graph package supervision/labels is missing or not a dict.")

    y = get_supervision_tensor(sup, "y", ndim=1).long()
    train_mask = get_supervision_tensor(sup, "train_mask", ndim=1).bool()
    val_mask = get_supervision_tensor(sup, "val_mask", ndim=1).bool()
    test_mask = get_supervision_tensor(sup, "test_mask", ndim=1).bool()

    if y.numel() != patient_x.size(0):
        raise ValueError(f"y length {y.numel()} != Patient node count {patient_x.size(0)}")

    num_classes = int(y.max().item()) + 1

    print(
        "[DirectLoader] Node features | "
        f"Patient={tuple(patient_x.shape)}, Drug={tuple(drug_x.shape)}, Procedure={tuple(proc_x.shape)}, "
        f"classes={num_classes}",
        flush=True,
    )
    print(
        "[DirectLoader] Splits | "
        f"train={int(train_mask.sum())}, val={int(val_mask.sum())}, test={int(test_mask.sum())}",
        flush=True,
    )

    return {
        "pt_path": str(pt_path),
        "pkg": pkg,
        "patient_x": patient_x,
        "drug_x": drug_x,
        "proc_x": proc_x,
        "y": y,
        "train_mask": train_mask,
        "val_mask": val_mask,
        "test_mask": test_mask,
        "num_classes": num_classes,
    }


# =============================================================================
# Edge extraction from raw package
# =============================================================================

def normalize_edge_key(key: Any) -> str:
    if isinstance(key, (tuple, list)):
        return "-".join(str(x) for x in key)
    return str(key)


def canonical_tuple(edge_item: Dict[str, Any], fallback_key: Any) -> Tuple[str, str, str]:
    can = edge_item.get("canonical_etype") if isinstance(edge_item, dict) else None
    if can is not None and len(can) == 3:
        return str(can[0]), str(can[1]), str(can[2])
    text = normalize_edge_key(fallback_key)
    parts = text.split("-")
    if len(parts) == 2:
        return parts[0], "rel", parts[1]
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    # weak fallback by keywords
    low = text.lower()
    if "patient" in low and "drug" in low:
        return "Patient", "rel", "Drug" if low.index("patient") < low.index("drug") else "Patient"
    if "patient" in low and ("procedure" in low or "proc" in low):
        return "Patient", "rel", "Procedure" if low.index("patient") < low.index("proc") else "Patient"
    return "", "rel", ""


def edge_item_to_patient_entity_edge(
    edge_item: Dict[str, Any],
    edge_key: Any,
    target_type: str,
    n_patient: int,
    n_target: int,
) -> Optional[torch.Tensor]:
    if not isinstance(edge_item, dict) or "edge_index" not in edge_item:
        return None
    ei = edge_item["edge_index"]
    if not torch.is_tensor(ei) or ei.dim() != 2:
        return None
    ei = ei.detach().cpu().long()
    if ei.size(0) != 2 and ei.size(1) == 2:
        ei = ei.t().contiguous()
    if ei.size(0) != 2:
        return None

    src_type, _, dst_type = canonical_tuple(edge_item, edge_key)
    key_text = normalize_edge_key(edge_key).lower()

    # Preferred: canonical etype.
    if src_type == "Patient" and dst_type == target_type:
        out = ei
    elif src_type == target_type and dst_type == "Patient":
        out = torch.stack([ei[1], ei[0]], dim=0)
    else:
        # Fallback from key name.
        if "patient" not in key_text:
            return None
        if target_type.lower() == "drug" and "drug" not in key_text:
            return None
        if target_type.lower() == "procedure" and not ("procedure" in key_text or "proc" in key_text):
            return None
        # If key starts with Patient, assume [patient, entity], otherwise reverse.
        if key_text.startswith("patient"):
            out = ei
        else:
            out = torch.stack([ei[1], ei[0]], dim=0)

    valid = (out[0] >= 0) & (out[0] < n_patient) & (out[1] >= 0) & (out[1] < n_target)
    out = out[:, valid].contiguous()
    return out


def get_patient_entity_edges(pkg: Dict[str, Any], target_type: str, n_patient: int, n_target: int) -> torch.Tensor:
    edges = pkg.get("edges") or pkg.get("edge_index_dict") or pkg.get("edge_data") or {}
    if not isinstance(edges, dict):
        raise KeyError("raw package has no dict-like edges/edge_index_dict/edge_data")

    candidates: List[torch.Tensor] = []
    for k, item in edges.items():
        key_text = normalize_edge_key(k).lower()
        if "patient" not in key_text:
            continue
        if target_type.lower() == "drug" and "drug" not in key_text:
            continue
        if target_type.lower() == "procedure" and not ("procedure" in key_text or "proc" in key_text):
            continue
        e = edge_item_to_patient_entity_edge(item, k, target_type, n_patient, n_target)
        if e is not None and e.numel() > 0:
            candidates.append(e)

    if not candidates:
        print(f"[WARN] No Patient-{target_type} edges found. Use empty edge_index.", flush=True)
        return torch.empty((2, 0), dtype=torch.long)

    out = torch.cat(candidates, dim=1)
    # Remove duplicated columns.
    if out.size(1) > 0:
        pair = out[0].numpy().astype(np.int64) * int(max(n_target, 1)) + out[1].numpy().astype(np.int64)
        _, idx = np.unique(pair, return_index=True)
        idx = np.sort(idx)
        out = out[:, torch.tensor(idx, dtype=torch.long)]

    print(f"[DirectLoader] Patient-{target_type} edges: {out.size(1)}", flush=True)
    return out.contiguous()


# =============================================================================
# PPR loading and mapping
# =============================================================================

def load_array_file(path: Path) -> Any:
    suf = path.suffix.lower()
    if suf == ".npy":
        return np.load(path, allow_pickle=False)
    if suf == ".npz":
        z = np.load(path, allow_pickle=True)
        return {k: z[k] for k in z.files}
    if suf in {".pt", ".pth"}:
        return torch_load(path)
    return None


def as_numpy(x: Any) -> Optional[np.ndarray]:
    if isinstance(x, np.ndarray):
        return x
    if torch.is_tensor(x):
        return x.detach().cpu().numpy()
    return None


def flatten_arrays(obj: Any, prefix: str = "") -> List[Tuple[str, np.ndarray]]:
    arr = as_numpy(obj)
    if arr is not None:
        return [(prefix, arr)]
    out: List[Tuple[str, np.ndarray]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.extend(flatten_arrays(v, f"{prefix}.{k}" if prefix else str(k)))
    elif isinstance(obj, (list, tuple)):
        for i, v in enumerate(obj):
            out.extend(flatten_arrays(v, f"{prefix}.{i}" if prefix else str(i)))
    return out


def load_dual_ppr_robust(ppr_dir: str, alpha: float = 0.5, data_name: str = "medical") -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    root = Path(ppr_dir)
    if not root.exists():
        raise FileNotFoundError(f"ppr_dir does not exist: {ppr_dir}")

    # First try exact CARE-4DD / medical_ppr names.
    alpha_candidates = []
    for a in [str(alpha), str(round(alpha, 2)), f"{alpha:.2f}", f"{alpha:.1f}"]:
        if a not in alpha_candidates:
            alpha_candidates.append(a)

    def exact(suffix: str, kind: str) -> Optional[np.ndarray]:
        prefix = "top_indices" if kind == "neigh" else "top_values"
        for a in alpha_candidates:
            p = root / f"{prefix}_alpha_{a}_{data_name}_{suffix}.npy"
            if p.exists():
                return np.load(p)
        return None

    nd = exact("drug", "neigh")
    vd = exact("drug", "value")
    np_ = exact("proc", "neigh")
    vp = exact("proc", "value")

    if nd is not None and np_ is not None:
        if vd is None:
            vd = np.zeros_like(nd, dtype=np.float32)
        if vp is None:
            vp = np.zeros_like(np_, dtype=np.float32)
        print(f"[PPR] Loaded exact files | drug={nd.shape}, proc={np_.shape}", flush=True)
        return nd.astype(np.int64), vd.astype(np.float32), np_.astype(np.int64), vp.astype(np.float32)

    # Robust fallback.
    arrays: List[Tuple[str, np.ndarray]] = []
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix.lower() not in {".npy", ".npz", ".pt", ".pth"}:
            continue
        try:
            arrays.extend(flatten_arrays(load_array_file(p), p.name))
        except Exception as exc:
            print(f"[WARN] Failed to read {p}: {exc}", flush=True)

    def find(kind: str, target: str) -> Optional[np.ndarray]:
        kind_words = [kind] if kind == "drug" else ["proc", "procedure"]
        neigh_words = ["neighbor", "neighbour", "indices", "index", "idx", "neigh"]
        value_words = ["value", "score", "weight", "prob", "ppr"]
        wanted = neigh_words if target == "neigh" else value_words
        best, best_score = None, -1
        for name, arr in arrays:
            if arr.ndim != 2:
                continue
            lname = name.lower()
            score = 0
            if any(w in lname for w in kind_words): score += 10
            if any(w in lname for w in wanted): score += 10
            if target == "neigh" and np.issubdtype(arr.dtype, np.integer): score += 5
            if target == "value" and np.issubdtype(arr.dtype, np.floating): score += 5
            if score > best_score:
                best, best_score = arr, score
        return best if best_score >= 15 else None

    nd, vd, np_, vp = find("drug", "neigh"), find("drug", "value"), find("proc", "neigh"), find("proc", "value")
    if nd is None or np_ is None:
        print("Available 2D PPR arrays:", flush=True)
        for name, arr in arrays:
            if arr.ndim == 2:
                print("  ", name, arr.shape, arr.dtype, flush=True)
        raise FileNotFoundError("Could not identify drug/procedure PPR neighbor arrays.")
    if vd is None:
        vd = np.zeros_like(nd, dtype=np.float32)
    if vp is None:
        vp = np.zeros_like(np_, dtype=np.float32)
    print(f"[PPR] Loaded robust files | drug={nd.shape}, proc={np_.shape}", flush=True)
    return nd.astype(np.int64), vd.astype(np.float32), np_.astype(np.int64), vp.astype(np.float32)


def map_ppr_for_patients(
    neigh: np.ndarray,
    values: np.ndarray,
    n_patient: int,
    n_drug: int,
    n_proc: int,
    target: str,
    k: int,
) -> Tuple[torch.Tensor, torch.Tensor]:
    if neigh.shape[0] < n_patient:
        raise ValueError(f"PPR rows {neigh.shape[0]} < patient nodes {n_patient}")

    neigh_p = neigh[:n_patient, :k].copy()
    val_p = values[:n_patient, :k].copy() if values is not None else np.zeros_like(neigh_p, dtype=np.float32)

    if target == "drug":
        local_valid = (neigh_p >= 0) & (neigh_p < n_drug)
        global_valid = (neigh_p >= n_patient) & (neigh_p < n_patient + n_drug)
        mapped = np.where(global_valid, neigh_p - n_patient, neigh_p)
        valid = local_valid | global_valid
        max_n = n_drug
    elif target == "proc":
        local_valid = (neigh_p >= 0) & (neigh_p < n_proc)
        proc_offset = n_patient + n_drug
        global_valid = (neigh_p >= proc_offset) & (neigh_p < proc_offset + n_proc)
        mapped = np.where(global_valid, neigh_p - proc_offset, neigh_p)
        valid = local_valid | global_valid
        max_n = n_proc
    else:
        raise ValueError(target)

    valid = valid & (mapped >= 0) & (mapped < max(max_n, 1))
    mapped = np.where(valid, mapped, -1).astype(np.int64)
    val_p = np.where(valid, val_p, 0.0).astype(np.float32)

    valid_rate = float(valid.mean()) if valid.size > 0 else 0.0
    print(f"[PPR] mapped {target} topK={k} | valid_rate={valid_rate:.4f}", flush=True)
    return torch.tensor(mapped, dtype=torch.long), torch.tensor(val_p, dtype=torch.float32)


# =============================================================================
# Dataset and metrics
# =============================================================================

class PatientIndexDataset(Dataset):
    def __init__(self, indices: torch.Tensor, y: torch.Tensor):
        self.indices = indices.detach().cpu().long()
        self.y = y.detach().cpu().long()

    def __len__(self) -> int:
        return int(self.indices.numel())

    def __getitem__(self, i: int) -> Tuple[torch.Tensor, torch.Tensor]:
        idx = self.indices[i]
        return idx, self.y[idx]


def safe_macro_ovr_auc_ap(y_true: np.ndarray, prob: np.ndarray, num_classes: int) -> Tuple[float, float]:
    aucs, aps = [], []
    for c in range(int(num_classes)):
        binary_true = (y_true == c).astype(int)
        if binary_true.sum() == 0 or binary_true.sum() == len(binary_true):
            continue
        score = prob[:, c]
        try:
            aucs.append(float(roc_auc_score(binary_true, score)))
        except Exception:
            pass
        try:
            aps.append(float(average_precision_score(binary_true, score)))
        except Exception:
            pass
    return float(np.mean(aucs)) if aucs else 0.0, float(np.mean(aps)) if aps else 0.0


def metrics_from_logits(logits: torch.Tensor, y: torch.Tensor, num_classes: int) -> Dict[str, float]:
    logits_cpu = logits.detach().cpu()
    y_cpu = y.detach().cpu().long()
    true = y_cpu.numpy().astype(int)
    pred = logits_cpu.argmax(dim=1).numpy().astype(int)
    prob = torch.softmax(logits_cpu, dim=1).numpy()

    acc = float(accuracy_score(true, pred))
    micro = float(f1_score(true, pred, average="micro", zero_division=0))
    macro = float(f1_score(true, pred, average="macro", zero_division=0))
    auroc, auprc = safe_macro_ovr_auc_ap(true, prob, num_classes)
    return {"accuracy": acc, "micro": micro, "macro": macro, "auroc": auroc, "auprc": auprc}


def build_class_weight(y: torch.Tensor, train_mask: torch.Tensor, num_classes: int, power: float, device: torch.device) -> torch.Tensor:
    counts = torch.bincount(y[train_mask].long(), minlength=num_classes).float().to(device).clamp_min(1.0)
    weight = counts.pow(-float(power))
    weight = weight / weight.mean()
    return weight


# =============================================================================
# Training / evaluation
# =============================================================================

class PreparedInputs:
    pass


def prepare_inputs(args: argparse.Namespace, device: torch.device) -> PreparedInputs:
    raw = load_raw_graph_package(args.dataset_path, split_name=args.split_name)

    n_patient = raw["patient_x"].size(0)
    n_drug = raw["drug_x"].size(0)
    n_proc = raw["proc_x"].size(0)

    pd_edge = get_patient_entity_edges(raw["pkg"], "Drug", n_patient, n_drug)
    pr_edge = get_patient_entity_edges(raw["pkg"], "Procedure", n_patient, n_proc)

    nd, vd, np_, vp = load_dual_ppr_robust(args.ppr_dir, alpha=args.alpha, data_name=args.data)

    # Match the original CARE-4DD patch allocation:
    # patch_size=64 -> 1 patient + 31 drug + 32 procedure.
    k_drug = max(0, args.patch_size // 2 - 1)
    k_proc = int(args.patch_size) - 1 - k_drug
    if k_drug <= 0 or k_proc <= 0:
        raise ValueError(f"Invalid patch_size={args.patch_size}; derived k_drug={k_drug}, k_proc={k_proc}")

    topk_drug, score_drug = map_ppr_for_patients(nd, vd, n_patient, n_drug, n_proc, "drug", k_drug)
    topk_proc, score_proc = map_ppr_for_patients(np_, vp, n_patient, n_drug, n_proc, "proc", k_proc)

    obj = PreparedInputs()
    obj.x_patient = raw["patient_x"].to(device)
    obj.x_drug = raw["drug_x"].to(device)
    obj.x_proc = raw["proc_x"].to(device)
    obj.y = raw["y"].to(device)
    obj.train_mask = raw["train_mask"].to(device)
    obj.val_mask = raw["val_mask"].to(device)
    obj.test_mask = raw["test_mask"].to(device)
    obj.num_classes = int(raw["num_classes"])
    obj.patient_drug_edge_index = pd_edge.to(device)
    obj.patient_proc_edge_index = pr_edge.to(device)
    obj.topk_drug = topk_drug.to(device)
    obj.topk_proc = topk_proc.to(device)
    obj.score_drug = score_drug.to(device)
    obj.score_proc = score_proc.to(device)
    obj.pt_path = raw["pt_path"]
    obj.k_drug = k_drug
    obj.k_proc = k_proc
    return obj


def make_model(args: argparse.Namespace, inp: PreparedInputs, device: torch.device) -> CARE4DD_HGConv:
    cfg = CARE4DDHGConvConfig(
        patient_in_dim=int(inp.x_patient.size(1)),
        drug_in_dim=int(inp.x_drug.size(1)),
        proc_in_dim=int(inp.x_proc.size(1)),
        num_classes=int(inp.num_classes),
        hidden_dim=int(args.hidden_dim),
        num_drug_tokens=int(inp.k_drug),
        num_proc_tokens=int(inp.k_proc),
        encoder_layers=int(args.encoder_layers),
        token_mlp_dim=None,
        channel_mlp_dim=int(args.hidden_dim) * int(args.mixer_expansion),
        dropout=float(args.dropout),
        use_hgconv=bool(args.use_hgconv),
        use_type_embedding=True,
    )
    return CARE4DD_HGConv(cfg).to(device)


def forward_batch(model: CARE4DD_HGConv, inp: PreparedInputs, patient_ids: torch.Tensor, return_embedding: bool = False):
    patient_ids = patient_ids.to(inp.y.device).long()
    return model(
        x_patient=inp.x_patient,
        x_drug=inp.x_drug,
        x_proc=inp.x_proc,
        patient_drug_edge_index=inp.patient_drug_edge_index,
        patient_proc_edge_index=inp.patient_proc_edge_index,
        batch_patient_ids=patient_ids,
        topk_drug_ids=inp.topk_drug[patient_ids],
        topk_proc_ids=inp.topk_proc[patient_ids],
        return_embedding=return_embedding,
    )


@torch.no_grad()
def evaluate(model: CARE4DD_HGConv, inp: PreparedInputs, indices: torch.Tensor, batch_size: int) -> Tuple[Dict[str, float], torch.Tensor, torch.Tensor]:
    model.eval()
    logits_all = []
    y_all = []
    for start in range(0, int(indices.numel()), int(batch_size)):
        ids = indices[start:start + int(batch_size)]
        logits = forward_batch(model, inp, ids, return_embedding=False)
        logits_all.append(logits.detach().cpu())
        y_all.append(inp.y[ids].detach().cpu())
    logits_all = torch.cat(logits_all, dim=0)
    y_all = torch.cat(y_all, dim=0)
    return metrics_from_logits(logits_all, y_all, inp.num_classes), logits_all, y_all


def train_one_run(args: argparse.Namespace, inp: PreparedInputs, run_id: int, device: torch.device) -> Dict[str, Any]:
    seed = int(args.seed) + int(run_id)
    set_seed(seed)
    model = make_model(args, inp, device)

    train_indices = torch.where(inp.train_mask.detach().cpu())[0]
    val_indices = torch.where(inp.val_mask.detach().cpu())[0]
    test_indices = torch.where(inp.test_mask.detach().cpu())[0]

    loader = DataLoader(
        PatientIndexDataset(train_indices, inp.y.detach().cpu()),
        batch_size=int(args.batch_size),
        shuffle=True,
        num_workers=0,
    )

    class_weight = None
    if args.use_class_weight:
        class_weight = build_class_weight(inp.y, inp.train_mask, inp.num_classes, args.class_weight_power, device)
        print(f"[Run {run_id}] class weights: {class_weight.detach().cpu().numpy().round(4).tolist()}", flush=True)

    criterion = nn.CrossEntropyLoss(weight=class_weight, label_smoothing=float(args.label_smoothing)).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=float(args.lr), weight_decay=float(args.weight_decay))
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(1, int(args.epochs)))

    best = {
        "epoch": -1,
        "val": {"macro": -1.0},
        "test": None,
        "state_dict": None,
    }
    bad = 0

    for epoch in range(1, int(args.epochs) + 1):
        model.train()
        total_loss = 0.0
        total_n = 0
        for batch_ids, batch_y in loader:
            batch_ids = batch_ids.to(device).long()
            batch_y = batch_y.to(device).long()
            optimizer.zero_grad(set_to_none=True)
            logits = forward_batch(model, inp, batch_ids, return_embedding=False)
            loss = criterion(logits, batch_y)
            loss.backward()
            if float(args.grad_clip) > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), float(args.grad_clip))
            optimizer.step()
            total_loss += float(loss.item()) * int(batch_ids.numel())
            total_n += int(batch_ids.numel())
        scheduler.step()

        val_metrics, _, _ = evaluate(model, inp, val_indices.to(device), args.eval_batch_size)
        test_metrics, _, _ = evaluate(model, inp, test_indices.to(device), args.eval_batch_size)
        train_loss = total_loss / max(1, total_n)

        if val_metrics["macro"] > best["val"].get("macro", -1.0):
            best = {
                "epoch": int(epoch),
                "train_loss": float(train_loss),
                "val": val_metrics,
                "test": test_metrics,
                "state_dict": {k: v.detach().cpu().clone() for k, v in model.state_dict().items()},
            }
            bad = 0
            flag = "*"
        else:
            bad += 1
            flag = ""

        if epoch == 1 or epoch % int(args.print_every) == 0 or flag:
            print(
                f"[Run {run_id}] Epoch {epoch:03d} | loss={train_loss:.4f} | "
                f"val micro/macro={val_metrics['micro']:.4f}/{val_metrics['macro']:.4f} | "
                f"test micro/macro={test_metrics['micro']:.4f}/{test_metrics['macro']:.4f} {flag}",
                flush=True,
            )
        if bad >= int(args.patience):
            print(f"[Run {run_id}] Early stop at epoch {epoch}, best epoch={best['epoch']}", flush=True)
            break

    if best["state_dict"] is not None:
        model.load_state_dict(best["state_dict"])
    final_test, test_logits, test_y = evaluate(model, inp, test_indices.to(device), args.eval_batch_size)

    # Optional t-SNE artifact for run 0.
    tsne_info = None
    if args.export_tsne and int(run_id) == int(args.tsne_run_id):
        model.eval()
        emb_list, y_list, pred_list, pid_list = [], [], [], []
        with torch.no_grad():
            for start in range(0, int(test_indices.numel()), int(args.eval_batch_size)):
                ids = test_indices[start:start + int(args.eval_batch_size)].to(device)
                logits, emb = forward_batch(model, inp, ids, return_embedding=True)
                emb_list.append(emb.detach().cpu().numpy())
                y_list.append(inp.y[ids].detach().cpu().numpy())
                pred_list.append(logits.argmax(dim=1).detach().cpu().numpy())
                pid_list.append(ids.detach().cpu().numpy())
        emb_np = np.concatenate(emb_list, axis=0)
        y_np = np.concatenate(y_list, axis=0)
        pred_np = np.concatenate(pred_list, axis=0)
        pid_np = np.concatenate(pid_list, axis=0)
        out_dir = Path(args.tsne_out_dir)
        ensure_dir(out_dir)
        out_path = out_dir / "care4dd_hgconv_test_embed.npz"
        np.savez_compressed(out_path, embeddings=emb_np.astype(np.float32), labels=y_np.astype(np.int64), predictions=pred_np.astype(np.int64), patient_ids=pid_np)
        out_path.with_suffix(".meta.json").write_text(json.dumps({
            "model_name": "CARE-4DD-HGConv" if args.use_hgconv else "CARE-4DD-noHGConv",
            "dataset_name": args.tsne_dataset_name,
            "num_samples": int(len(y_np)),
            "embedding_dim": int(emb_np.shape[1]),
        }, ensure_ascii=False, indent=2), encoding="utf-8")
        tsne_info = str(out_path)
        print(f"[t-SNE] Saved: {out_path}", flush=True)

    return {
        "run_id": int(run_id),
        "seed": int(seed),
        "best_epoch": int(best["epoch"]),
        "best_val": best["val"],
        "best_test": best["test"],
        "final": {"best_test": final_test},
        "final_stage": "stage1_hgconv" if args.use_hgconv else "stage1_no_hgconv",
        "tsne_artifact": tsne_info,
    }


def aggregate_results(results: List[Dict[str, Any]]) -> Dict[str, float]:
    def arr(metric: str) -> np.ndarray:
        return np.array([float(r["final"]["best_test"][metric]) for r in results], dtype=float)
    out = {}
    for key, paper_key in [
        ("micro", "final_test_micro"),
        ("macro", "final_test_macro"),
        ("auroc", "final_test_auroc"),
        ("auprc", "final_test_auprc"),
        ("accuracy", "final_test_accuracy"),
    ]:
        vals = arr(key)
        out[f"{paper_key}_mean"] = float(vals.mean())
        out[f"{paper_key}_std"] = float(vals.std(ddof=1)) if len(vals) > 1 else 0.0
    return out


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset_path", type=str, required=True)
    ap.add_argument("--split_name", type=str, default="active_split")
    ap.add_argument("--ppr_dir", type=str, required=True)
    ap.add_argument("--data", type=str, default="medical")
    ap.add_argument("--alpha", type=float, default=0.5)
    ap.add_argument("--patch_size", type=int, default=64)

    ap.add_argument("--hidden_dim", type=int, default=64)
    ap.add_argument("--encoder_layers", type=int, default=3)
    ap.add_argument("--mixer_expansion", type=int, default=2)
    ap.add_argument("--dropout", type=float, default=0.10)

    hg = ap.add_mutually_exclusive_group()
    hg.add_argument("--use_hgconv", action="store_true", help="Enable lightweight heterogeneous graph convolution.")
    hg.add_argument("--no_hgconv", action="store_false", dest="use_hgconv", help="Disable heterogeneous graph convolution.")
    ap.set_defaults(use_hgconv=True)

    ap.add_argument("--runs", type=int, default=3)
    ap.add_argument("--seed", type=int, default=729)
    ap.add_argument("--epochs", type=int, default=80)
    ap.add_argument("--patience", type=int, default=12)
    ap.add_argument("--batch_size", type=int, default=512)
    ap.add_argument("--eval_batch_size", type=int, default=512)
    ap.add_argument("--lr", type=float, default=8e-4)
    ap.add_argument("--weight_decay", type=float, default=8e-3)
    ap.add_argument("--label_smoothing", type=float, default=0.08)
    ap.add_argument("--use_class_weight", action="store_true")
    ap.add_argument("--class_weight_power", type=float, default=0.6)
    ap.add_argument("--grad_clip", type=float, default=1.0)
    ap.add_argument("--print_every", type=int, default=1)

    # compatibility flags, accepted but not functionally needed here
    ap.add_argument("--stage1_only", action="store_true")
    ap.add_argument("--save_summary", action="store_true")
    ap.add_argument("--save_dir", type=str, default="./outputs/care4dd_hgconv_direct")
    ap.add_argument("--device", type=str, default="cuda", choices=["cuda", "cpu"])
    ap.add_argument("--device_num", type=int, default=-1)

    ap.add_argument("--export_tsne", action="store_true")
    ap.add_argument("--tsne_run_id", type=int, default=0)
    ap.add_argument("--tsne_out_dir", type=str, default="./outputs/tsne_artifacts")
    ap.add_argument("--tsne_dataset_name", type=str, default="MIMIC-IV")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    device = select_device(args)
    print("=" * 100, flush=True)
    print(f"Device: {device}", flush=True)
    print(f"Use HGConv: {args.use_hgconv}", flush=True)
    print("=" * 100, flush=True)

    save_dir = Path(args.save_dir)
    ensure_dir(save_dir)

    # Save config early.
    (save_dir / "config.json").write_text(json.dumps(vars(args), ensure_ascii=False, indent=2), encoding="utf-8")

    # Load once; reused across runs.
    prepared = prepare_inputs(args, device)

    results = []
    start = time.perf_counter()
    for run_id in range(int(args.runs)):
        print("\n" + "=" * 100, flush=True)
        print(f"Run {run_id}/{int(args.runs)-1}", flush=True)
        print("=" * 100, flush=True)
        results.append(train_one_run(args, prepared, run_id, device))

    aggregate = aggregate_results(results)
    elapsed = time.perf_counter() - start

    summary = {
        "config": vars(args),
        "data": {
            "graph_pt": prepared.pt_path,
            "patient_shape": list(prepared.x_patient.shape),
            "drug_shape": list(prepared.x_drug.shape),
            "procedure_shape": list(prepared.x_proc.shape),
            "patient_drug_edges": int(prepared.patient_drug_edge_index.size(1)),
            "patient_procedure_edges": int(prepared.patient_proc_edge_index.size(1)),
            "k_drug": int(prepared.k_drug),
            "k_proc": int(prepared.k_proc),
        },
        "results": results,
        "aggregate": aggregate,
        "elapsed_sec": float(elapsed),
    }
    summary_path = save_dir / "summary.json"
    summary_path.write_text(json.dumps(to_jsonable(summary), ensure_ascii=False, indent=2), encoding="utf-8")

    print("\nSUMMARY", flush=True)
    print(f"Final Test Micro-F1: {aggregate['final_test_micro_mean']:.4f} ± {aggregate['final_test_micro_std']:.4f}", flush=True)
    print(f"Final Test Macro-F1: {aggregate['final_test_macro_mean']:.4f} ± {aggregate['final_test_macro_std']:.4f}", flush=True)
    print(f"Final Test AUROC:    {aggregate['final_test_auroc_mean']:.4f} ± {aggregate['final_test_auroc_std']:.4f}", flush=True)
    print(f"Final Test AUPRC:    {aggregate['final_test_auprc_mean']:.4f} ± {aggregate['final_test_auprc_std']:.4f}", flush=True)
    print(f"Saved summary to: {summary_path}", flush=True)


if __name__ == "__main__":
    main()
